[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mongo-validator"
version = "1.0.0"
description = "Generate MongoDB validation schemas from Python type annotations and Pydantic models."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.6",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
